// Code generated by protoc-gen-go. DO NOT EDIT.
// source: request.proto

package heartbeat

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RequestHeader struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ServerType           string   `protobuf:"bytes,2,opt,name=server_type,json=serverType,proto3" json:"server_type,omitempty"`
	CmdType              string   `protobuf:"bytes,3,opt,name=cmd_type,json=cmdType,proto3" json:"cmd_type,omitempty"`
	Version              string   `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestHeader) Reset()         { *m = RequestHeader{} }
func (m *RequestHeader) String() string { return proto.CompactTextString(m) }
func (*RequestHeader) ProtoMessage()    {}
func (*RequestHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{0}
}

func (m *RequestHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestHeader.Unmarshal(m, b)
}
func (m *RequestHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestHeader.Marshal(b, m, deterministic)
}
func (m *RequestHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestHeader.Merge(m, src)
}
func (m *RequestHeader) XXX_Size() int {
	return xxx_messageInfo_RequestHeader.Size(m)
}
func (m *RequestHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestHeader.DiscardUnknown(m)
}

var xxx_messageInfo_RequestHeader proto.InternalMessageInfo

func (m *RequestHeader) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RequestHeader) GetServerType() string {
	if m != nil {
		return m.ServerType
	}
	return ""
}

func (m *RequestHeader) GetCmdType() string {
	if m != nil {
		return m.CmdType
	}
	return ""
}

func (m *RequestHeader) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

//此结构为消息中间件中的数据传输格式，其中cmdType供服务中自行区分解析
//加上发送方的sender_id, 接受的userId
type MsgBody struct {
	SenderId             string   `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	CmdType              string   `protobuf:"bytes,2,opt,name=cmd_type,json=cmdType,proto3" json:"cmd_type,omitempty"`
	MsgBytes             []byte   `protobuf:"bytes,3,opt,name=msg_bytes,json=msgBytes,proto3" json:"msg_bytes,omitempty"`
	Version              string   `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MsgBody) Reset()         { *m = MsgBody{} }
func (m *MsgBody) String() string { return proto.CompactTextString(m) }
func (*MsgBody) ProtoMessage()    {}
func (*MsgBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{1}
}

func (m *MsgBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MsgBody.Unmarshal(m, b)
}
func (m *MsgBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MsgBody.Marshal(b, m, deterministic)
}
func (m *MsgBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgBody.Merge(m, src)
}
func (m *MsgBody) XXX_Size() int {
	return xxx_messageInfo_MsgBody.Size(m)
}
func (m *MsgBody) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgBody.DiscardUnknown(m)
}

var xxx_messageInfo_MsgBody proto.InternalMessageInfo

func (m *MsgBody) GetSenderId() string {
	if m != nil {
		return m.SenderId
	}
	return ""
}

func (m *MsgBody) GetCmdType() string {
	if m != nil {
		return m.CmdType
	}
	return ""
}

func (m *MsgBody) GetMsgBytes() []byte {
	if m != nil {
		return m.MsgBytes
	}
	return nil
}

func (m *MsgBody) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type TokenTcpRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Version              string   `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenTcpRequest) Reset()         { *m = TokenTcpRequest{} }
func (m *TokenTcpRequest) String() string { return proto.CompactTextString(m) }
func (*TokenTcpRequest) ProtoMessage()    {}
func (*TokenTcpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{2}
}

func (m *TokenTcpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenTcpRequest.Unmarshal(m, b)
}
func (m *TokenTcpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenTcpRequest.Marshal(b, m, deterministic)
}
func (m *TokenTcpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenTcpRequest.Merge(m, src)
}
func (m *TokenTcpRequest) XXX_Size() int {
	return xxx_messageInfo_TokenTcpRequest.Size(m)
}
func (m *TokenTcpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenTcpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TokenTcpRequest proto.InternalMessageInfo

func (m *TokenTcpRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *TokenTcpRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *TokenTcpRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *TokenTcpRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type TokenTcpRespone struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TokenTcpRespone) Reset()         { *m = TokenTcpRespone{} }
func (m *TokenTcpRespone) String() string { return proto.CompactTextString(m) }
func (*TokenTcpRespone) ProtoMessage()    {}
func (*TokenTcpRespone) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{3}
}

func (m *TokenTcpRespone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TokenTcpRespone.Unmarshal(m, b)
}
func (m *TokenTcpRespone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TokenTcpRespone.Marshal(b, m, deterministic)
}
func (m *TokenTcpRespone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TokenTcpRespone.Merge(m, src)
}
func (m *TokenTcpRespone) XXX_Size() int {
	return xxx_messageInfo_TokenTcpRespone.Size(m)
}
func (m *TokenTcpRespone) XXX_DiscardUnknown() {
	xxx_messageInfo_TokenTcpRespone.DiscardUnknown(m)
}

var xxx_messageInfo_TokenTcpRespone proto.InternalMessageInfo

func (m *TokenTcpRespone) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *TokenTcpRespone) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *TokenTcpRespone) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type LoginRequest struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserName             string   `protobuf:"bytes,2,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Token                string   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	LoginType            uint32   `protobuf:"varint,5,opt,name=login_type,json=loginType,proto3" json:"login_type,omitempty"`
	Version              string   `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{4}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *LoginRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *LoginRequest) GetLoginType() uint32 {
	if m != nil {
		return m.LoginType
	}
	return 0
}

func (m *LoginRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type LoginRespone struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Code                 uint32   `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	LoginState           uint32   `protobuf:"varint,3,opt,name=login_state,json=loginState,proto3" json:"login_state,omitempty"`
	Oms                  string   `protobuf:"bytes,4,opt,name=oms,proto3" json:"oms,omitempty"`
	Version              string   `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRespone) Reset()         { *m = LoginRespone{} }
func (m *LoginRespone) String() string { return proto.CompactTextString(m) }
func (*LoginRespone) ProtoMessage()    {}
func (*LoginRespone) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{5}
}

func (m *LoginRespone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRespone.Unmarshal(m, b)
}
func (m *LoginRespone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRespone.Marshal(b, m, deterministic)
}
func (m *LoginRespone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRespone.Merge(m, src)
}
func (m *LoginRespone) XXX_Size() int {
	return xxx_messageInfo_LoginRespone.Size(m)
}
func (m *LoginRespone) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRespone.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRespone proto.InternalMessageInfo

func (m *LoginRespone) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *LoginRespone) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *LoginRespone) GetLoginState() uint32 {
	if m != nil {
		return m.LoginState
	}
	return 0
}

func (m *LoginRespone) GetOms() string {
	if m != nil {
		return m.Oms
	}
	return ""
}

func (m *LoginRespone) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type HeartBeatReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartBeatReq) Reset()         { *m = HeartBeatReq{} }
func (m *HeartBeatReq) String() string { return proto.CompactTextString(m) }
func (*HeartBeatReq) ProtoMessage()    {}
func (*HeartBeatReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{6}
}

func (m *HeartBeatReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeatReq.Unmarshal(m, b)
}
func (m *HeartBeatReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeatReq.Marshal(b, m, deterministic)
}
func (m *HeartBeatReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeatReq.Merge(m, src)
}
func (m *HeartBeatReq) XXX_Size() int {
	return xxx_messageInfo_HeartBeatReq.Size(m)
}
func (m *HeartBeatReq) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeatReq.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeatReq proto.InternalMessageInfo

func (m *HeartBeatReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *HeartBeatReq) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type HeartBeatRsp struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Code                 int64    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Timestamp            int64    `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Version              string   `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HeartBeatRsp) Reset()         { *m = HeartBeatRsp{} }
func (m *HeartBeatRsp) String() string { return proto.CompactTextString(m) }
func (*HeartBeatRsp) ProtoMessage()    {}
func (*HeartBeatRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{7}
}

func (m *HeartBeatRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HeartBeatRsp.Unmarshal(m, b)
}
func (m *HeartBeatRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HeartBeatRsp.Marshal(b, m, deterministic)
}
func (m *HeartBeatRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeartBeatRsp.Merge(m, src)
}
func (m *HeartBeatRsp) XXX_Size() int {
	return xxx_messageInfo_HeartBeatRsp.Size(m)
}
func (m *HeartBeatRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_HeartBeatRsp.DiscardUnknown(m)
}

var xxx_messageInfo_HeartBeatRsp proto.InternalMessageInfo

func (m *HeartBeatRsp) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *HeartBeatRsp) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *HeartBeatRsp) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *HeartBeatRsp) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type CommunicateReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommunicateReq) Reset()         { *m = CommunicateReq{} }
func (m *CommunicateReq) String() string { return proto.CompactTextString(m) }
func (*CommunicateReq) ProtoMessage()    {}
func (*CommunicateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{8}
}

func (m *CommunicateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommunicateReq.Unmarshal(m, b)
}
func (m *CommunicateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommunicateReq.Marshal(b, m, deterministic)
}
func (m *CommunicateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommunicateReq.Merge(m, src)
}
func (m *CommunicateReq) XXX_Size() int {
	return xxx_messageInfo_CommunicateReq.Size(m)
}
func (m *CommunicateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CommunicateReq.DiscardUnknown(m)
}

var xxx_messageInfo_CommunicateReq proto.InternalMessageInfo

func (m *CommunicateReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CommunicateReq) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *CommunicateReq) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type CommunicateRsp struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Code                 int64    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommunicateRsp) Reset()         { *m = CommunicateRsp{} }
func (m *CommunicateRsp) String() string { return proto.CompactTextString(m) }
func (*CommunicateRsp) ProtoMessage()    {}
func (*CommunicateRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{9}
}

func (m *CommunicateRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommunicateRsp.Unmarshal(m, b)
}
func (m *CommunicateRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommunicateRsp.Marshal(b, m, deterministic)
}
func (m *CommunicateRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommunicateRsp.Merge(m, src)
}
func (m *CommunicateRsp) XXX_Size() int {
	return xxx_messageInfo_CommunicateRsp.Size(m)
}
func (m *CommunicateRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_CommunicateRsp.DiscardUnknown(m)
}

var xxx_messageInfo_CommunicateRsp proto.InternalMessageInfo

func (m *CommunicateRsp) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CommunicateRsp) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *CommunicateRsp) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterType((*RequestHeader)(nil), "heartbeat.RequestHeader")
	proto.RegisterType((*MsgBody)(nil), "heartbeat.MsgBody")
	proto.RegisterType((*TokenTcpRequest)(nil), "heartbeat.TokenTcpRequest")
	proto.RegisterType((*TokenTcpRespone)(nil), "heartbeat.TokenTcpRespone")
	proto.RegisterType((*LoginRequest)(nil), "heartbeat.LoginRequest")
	proto.RegisterType((*LoginRespone)(nil), "heartbeat.LoginRespone")
	proto.RegisterType((*HeartBeatReq)(nil), "heartbeat.HeartBeatReq")
	proto.RegisterType((*HeartBeatRsp)(nil), "heartbeat.HeartBeatRsp")
	proto.RegisterType((*CommunicateReq)(nil), "heartbeat.CommunicateReq")
	proto.RegisterType((*CommunicateRsp)(nil), "heartbeat.CommunicateRsp")
}

func init() { proto.RegisterFile("request.proto", fileDescriptor_7f73548e33e655fe) }

var fileDescriptor_7f73548e33e655fe = []byte{
	// 447 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0x4b, 0x8f, 0xd3, 0x30,
	0x10, 0x56, 0x9a, 0x3e, 0x92, 0xd9, 0x06, 0x50, 0x84, 0x44, 0xa1, 0x20, 0xaa, 0x9e, 0x7a, 0xda,
	0x0b, 0x47, 0x4e, 0x94, 0xcb, 0xae, 0x04, 0x1c, 0x4c, 0x25, 0xa4, 0x95, 0x50, 0xe5, 0xc6, 0xa3,
	0x10, 0x81, 0x63, 0xaf, 0xc7, 0x5d, 0xe8, 0x01, 0xce, 0xfc, 0x1b, 0xfe, 0x22, 0xb2, 0x1d, 0xda,
	0x04, 0xa9, 0xe5, 0x21, 0xed, 0x2d, 0xf3, 0x7d, 0xd5, 0xf7, 0x70, 0xc7, 0x86, 0xcc, 0xe0, 0xf5,
	0x16, 0xc9, 0x9e, 0x6b, 0xa3, 0xac, 0xca, 0xd3, 0x0f, 0xc8, 0x8d, 0xdd, 0x20, 0xb7, 0xf3, 0x6f,
	0x90, 0xb1, 0xc0, 0x5d, 0x20, 0x17, 0x68, 0xf2, 0x07, 0x30, 0xda, 0x12, 0x9a, 0x75, 0x25, 0x26,
	0xd1, 0x2c, 0x5a, 0xc4, 0x6c, 0xe8, 0xc6, 0x4b, 0x91, 0x3f, 0x85, 0x33, 0x42, 0x73, 0x83, 0x66,
	0x6d, 0x77, 0x1a, 0x27, 0xbd, 0x59, 0xb4, 0x48, 0x19, 0x04, 0x68, 0xb5, 0xd3, 0x98, 0x3f, 0x84,
	0xa4, 0x90, 0x22, 0xb0, 0xb1, 0x67, 0x47, 0x85, 0x14, 0x9e, 0x9a, 0xc0, 0xe8, 0x06, 0x0d, 0x55,
	0xaa, 0x9e, 0xf4, 0x03, 0xd3, 0x8c, 0xf3, 0x2f, 0x30, 0x7a, 0x4d, 0xe5, 0x52, 0x89, 0x5d, 0x3e,
	0x85, 0x94, 0xb0, 0x16, 0x07, 0xef, 0x94, 0x25, 0x01, 0xb8, 0x14, 0x1d, 0xf1, 0x5e, 0x57, 0x7c,
	0x0a, 0xa9, 0xa4, 0x72, 0xbd, 0xd9, 0x59, 0x24, 0x6f, 0x3c, 0x66, 0x89, 0xa4, 0x72, 0xe9, 0xe6,
	0x13, 0xce, 0x5f, 0xe1, 0xee, 0x4a, 0x7d, 0xc4, 0x7a, 0x55, 0xe8, 0xe6, 0x04, 0x8e, 0x77, 0x9f,
	0x42, 0xea, 0x89, 0x9a, 0xcb, 0x5f, 0xf6, 0x89, 0x03, 0xde, 0x70, 0x89, 0xf9, 0x23, 0x48, 0x34,
	0x27, 0xfa, 0xac, 0x8c, 0x68, 0x7a, 0xef, 0xe7, 0x13, 0xf6, 0x57, 0x6d, 0x7b, 0xd2, 0xaa, 0xc6,
	0xe3, 0xf6, 0xf7, 0x61, 0x60, 0xdd, 0x6f, 0x1b, 0xeb, 0x30, 0xb4, 0xb5, 0xe3, 0xae, 0xf6, 0x8f,
	0x08, 0xc6, 0xaf, 0x54, 0x59, 0xd5, 0xb7, 0x57, 0x6c, 0x1f, 0xa9, 0xdf, 0x8e, 0xf4, 0x04, 0xe0,
	0x93, 0xf3, 0x0d, 0xff, 0xd3, 0x60, 0x16, 0x2d, 0x32, 0x96, 0x7a, 0xe4, 0xf7, 0x35, 0x18, 0x76,
	0x13, 0x7f, 0x3f, 0x24, 0xfe, 0xc3, 0x59, 0xe4, 0xd0, 0x2f, 0x94, 0x08, 0x61, 0x33, 0xe6, 0xbf,
	0xdd, 0x6a, 0x06, 0x5b, 0xb2, 0xdc, 0x86, 0xe5, 0xcb, 0x58, 0x48, 0xf2, 0xd6, 0x21, 0xf9, 0x3d,
	0x88, 0x95, 0xa4, 0x26, 0xab, 0xfb, 0x6c, 0x47, 0x19, 0x74, 0xa3, 0xbc, 0x80, 0xf1, 0x85, 0xbb,
	0x1e, 0x4b, 0xe4, 0x96, 0xe1, 0xf5, 0xf1, 0x24, 0x2d, 0x89, 0x5e, 0x57, 0x82, 0xda, 0x12, 0xa4,
	0xff, 0xae, 0x4c, 0xdc, 0x94, 0x79, 0x0c, 0xa9, 0xad, 0x24, 0x92, 0xe5, 0x52, 0xfb, 0x2a, 0x31,
	0x3b, 0x00, 0x27, 0x16, 0xea, 0x3d, 0xdc, 0x79, 0xa9, 0xa4, 0xdc, 0xd6, 0x55, 0xc1, 0x2d, 0xfe,
	0x5f, 0x72, 0xc7, 0x48, 0x24, 0xe2, 0xe5, 0xfe, 0x0a, 0x37, 0xe3, 0xfc, 0x5d, 0x57, 0xfe, 0x5f,
	0x5b, 0x1d, 0x5d, 0xd6, 0x65, 0x76, 0x75, 0x76, 0xfe, 0x7c, 0xff, 0x20, 0x6d, 0x86, 0xfe, 0x89,
	0x7a, 0xf6, 0x33, 0x00, 0x00, 0xff, 0xff, 0x21, 0xf6, 0x1a, 0x16, 0xb3, 0x04, 0x00, 0x00,
}
